### DISCUSSION TITLE
alone normal, hold for multi modifers?

### DISCUSSION THREAD

**Discussion by stuart-warren** [xremap/xremap#405] [Q&A] [answered]
first off, I really like this tool and can see a lot of potential, so thank you!

is it possible to have a key that when pressed alone performs its normal function, but when held is multiple modifiers?

my home row works fine configured similar to https://github.com/manna-harbour/miryoku, with single modifiers

I have other keys I'd like to work similar with multiple modifiers when held. eg: Press R alone, output R. Hold R, output meta(windows?), alt, ctrl, shift

thanks

**Comment by jixiuf** [comment, marked as answer]
maybe:
```
modmap:
  - name: Global
    remap:
      space:
        held: [ctrl_l,super_l]
        alone: space
        alone_timeout_millis: 1000 # Optional
```
