### DISCUSSION TITLE
How would I go about mapping KEY_SPACE-j to KEY_DOWN?

### DISCUSSION THREAD

**Discussion by ct400** [xremap/xremap#421] [Q&A]
And, of course, the other Vim-keys. Space should be space alone, but when held in combination with h,j,k,l it should be the relevant arrow-key movement.

Is this doable, currently?

Many thanks!

**Comment by k0kubun** [comment]
Here's one way to do it:

```yml
modmap:
  - remap:
      Space:
        held: Alt_L
        alone: Space
keymap:
  - remap:
      Alt-j: Down
```
