### DISCUSSION TITLE
Unexpected 'unknown key' showing for 'Super-Space' in modmap section.

### DISCUSSION THREAD

**Discussion by TimmermanV** [xremap/xremap#431] [Q&A] [answered]
I'm trying to remap Super/Win - Spacebar to just a single press on the Super key, but somehow `Super-Space` is not recognised by xremap in the modmap section. From what I'm reading I thought that the following would work:
```
modmap:
  - name: Test mappings
    remap:
      Super-Space: Super
      Super_L: Control_L
      Super_R: Control_R
```

The bottom two do work (if I remove the first mapping). The first shows this error:
```
Error: Failed to load config 'xremap.yml': modmap[0].remap: unknown key 'Super-Space' at line 4 column 7
```

I'm a bit lost and hope someone here could tell me what I'm doing wrong. :-)

**Comment by k0kubun** [comment]
`modmap` doesn't support key combinations. You need to put `Super-Space: Super` under `keymap`.

**Reply by TimmermanV** [reply]
I glossed over that, sorry! I think I read this "Note that remapping a key to a modifier key, e.g. CapsLock to Control_L" and I'm mapping to a modifier key (Super) so I wasn't sure if that would work.

Now that I'm trying this, I don't think these rules can work together? What I'm trying is to remap Super (which on my MacBook is the Command key) to Control, except for Super-Space which should trigger just a Super keypress. (to reveal the Pop Os universal search window)

**Reply by k0kubun** [reply, marked as answer]
You changed both Super_L and Super_R to something else before `keymap` happens, so `Control-Space` seems like what you actually want. You could also use `Control_L-Space` or `Control_R-Space` if you want to limit it to (original) Super_L or Super_R.

**Comment by TimmermanV** [comment]
Ah, so modmap is already in effect for keymap. That I missed as well. This was super helpful. It looks like this does the trick:
```
modmap:
  - name: Map command to right control
    remap:
      Super_L: Control_R
      Super_R: Control_R

keymap:
  - name: Map command space to command
    remap:
      Control_R-Space: Super_L
```

The nice thing here is that the right control key does not exist on my macbook, so I'm sure that key press is actually the super/command key.

Thanks for your help!
