### DISCUSSION TITLE
Remap Shift-Esc to tildes

### DISCUSSION THREAD

**Discussion by yayuwang0624** [xremap/xremap#473] [Q&A] [answered]
I have tried `KEY_RIGHTSHIFT-KEY_ESC` and `Shift-Esc` both cause error: `Error: Failed to load config 'xremap/config.yml': modmap[0].remap: unknown key '...'`

Does anyone know if this is doable?

**Comment by k0kubun** [comment]
Please share an entire YAML file.

**Reply by yayuwang0624** [reply]
Sure. Here is the config
```
modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      Shift-Esc: Shift-KEY_GRAVE
```

and the error is `Error: Failed to load config '~/.config/xremap/config.yml': modmap[0].remap: unknown key 'Shift-Esc' at line 4 column 7`
