### DISCUSSION TITLE
How to quote the next key? (`C-q`)

### DISCUSSION THREAD

**Discussion by WJCFerguson** [xremap/xremap#475] [Q&A] [answered]
With xkeysnail I would have `C-q` to "quote" the next key pressed, i.e. pass it through unmolested.

I seem to have achieved this with a bit of a hack but is this the "right" way?  Whatever is the right way would be nice to have in the `emacs.yml`.

I appended this hack to `emacs.yml` and made `C-q` do a null remap:

``` yaml
      ...
      C-q:                      # quote next char
        remap:
          a: a
```

Seems to work.  Is there a better way?

(Thanks for this - essential to get me using Wayland!)

**Comment by k0kubun** [comment, marked as answer]
It's

```yml
keymap:
  - remap:
      C-q: { escape_next_key: true }    
```
