### DISCUSSION TITLE
`Left shift + right Shift` toggles `CapsLock` and any shift key  `removes` Capslock

### DISCUSSION THREAD

**Discussion by OmiChrome** [xremap/xremap#519] [Q&A] [answered]
i still use `Capslock` as `esc` and Capslock hold as control so Capslock key feature become Obsolete.
### and `single SHIFT key press` to `remove/toggle off Capslock`. 

>  i used to have this in kde settings . but not using kde anymore

**Comment by k0kubun** [comment]
xremap is a key remapper. It is definitely possible to remap "pressing BOTH shift keys" and "single SHIFT key press" to something. But you need to know what key or command achieves the thing.

I think you can toggle CapsLock by just emitting a regular CapsLock key. However, I have no idea how to remove/toggle off CapsLock. Without any key remapper, what kind of key or command do you use to achieve that?

If you can't achieve it outside KDE, xremap can't either. It is not a desktop environment like KDE but a key remapper.

**Reply by cmm** [reply]
> It is definitely possible to remap "pressing BOTH shift keys"

I'm totally failing to do that, actually.  Tried this:
```
keymap:
  - name: Both shifts as CapsLock
    remap:
      Shift_L-RightShift: CapsLock
      Shift_R-LeftShift: CapsLock
```
Also tried with just `Shift` as modifier.  No dice.

`CapsLock` is definitely a legal target -- currently I have a modmap where tapping any Shift key is CapsLock and it works (except I toggle it too often and would like a less accessible alternative, like both Shifts...)

**Reply by cmm** [reply, marked as answer]
@NormTurtle FTR: I got it working, but I wonder if there's a simpler way
```
shared:
        shift_when_Off: &shift_when_Off
             press: { set_mode: Shift }

        shift_when_Shift: &shift_when_Shift
             press: [ { press: CapsLock }, { set_mode: Two_Shifts } ]
             release: { set_mode: Off }

        shift_when_Two_Shifts: &shift_when_Two_Shifts
             release: [ { release: CapsLock }, { set_mode: Off } ]

modmap:
          - name: Shift when Off
            mode: Off
            remap:
                Shift_L: *shift_when_Off
                Shift_R: *shift_when_Off

          - name: Shift when Shift
            mode: Shift
            remap:
                Shift_L: *shift_when_Shift
                Shift_R: *shift_when_Shift

          - name: Shift when Two Shifts
            mode: Two_Shifts
            remap:
                Shift_L: *shift_when_Two_Shifts
                Shift_R: *shift_when_Two_Shifts

default_mode: Off
```

**Reply by hpccc53** [reply]
It's possible to reduce it a little by releasing capslock already when second shift is pressed.

```yml
shared:
  shift_when_Off: &shift_when_Off
    press: { set_mode: Shift }

  shift_when_Shift: &shift_when_Shift
    press: capslock
    release: { set_mode: Off }

modmap:
  - name: Shift when Off
    mode: Off
    remap:
      Shift_L: *shift_when_Off
      Shift_R: *shift_when_Off

  - name: Shift when Shift
    mode: Shift
    remap:
      Shift_L: *shift_when_Shift
      Shift_R: *shift_when_Shift

default_mode: Off
```

**Reply by cmm** [reply]
actually I think 3 modes are kinda required if you want the intuitive CapsLock toggling behavior when you keep one Shift key down and repeatedly press the other one.  like this:
```
shared:
        shift_when_Off: &shift_when_Off
             press: { set_mode: Shift }

        shift_when_Shift: &shift_when_Shift
             press: [ CapsLock, { set_mode: Two_Shifts } ]
             release: { set_mode: Off }

        shift_when_Two_Shifts: &shift_when_Two_Shifts
             release: { set_mode: Shift }

modmap:
          # Shift-Shift is CapsLock
          - mode: Off
            remap:
                Shift_L: *shift_when_Off
                Shift_R: *shift_when_Off
          - mode: Shift
            remap:
                Shift_L: *shift_when_Shift
                Shift_R: *shift_when_Shift
          - mode: Two_Shifts
            remap:
                Shift_L: *shift_when_Two_Shifts
                Shift_R: *shift_when_Two_Shifts

default_mode: Off
```
(and now I'm irritated that there's no apparent way to prevent Xremap from spamming the logs about mode changes.  I mean I get why it does that, but knowing every time I press a Shift key is maybe too much information?)
