### DISCUSSION TITLE
[Feature request] Add support for matching window's instance or title

### DISCUSSION THREAD

**Discussion by kohane27** [xremap/xremap#588] [Ideas]
Hello @k0kubun. Hope you're doing well. Thank you for creating this awesome remap software.

I'm trying to match against an instance of Chrome. Relevant output from `swaymsg -t get_tree`:

```
  "name": "Amplenote - Personal - Amplenote",
  "window": 14680222,
  "sticky": false,
  "pid": 3029,
  "app_id": null,
  "visible": true,
  "shell": "xwayland",
  "window_properties": {
    "class": "Chromium",
    "instance": "crx_pfphkenhllngngioolkalhlmi",
    "title": "Amplenote - Personal - Amplenote",
    "transient_for": null,
    "window_role": "pop-up",
    "window_type": "normal"
  }
}
```

As you could see, `"app_id": null`, but we do have other useful info like:

```
"class": "Chromium",
"instance": "crx_pfphkenhllngngioolkalhlmi",
"title": "Amplenote - Personal - Amplenote",
```

Given regex support is recently implemented ([#138](https://github.com/k0kubun/xremap/pull/138)),I tried the following but to no avail:

```yml
  - name: Amplenote
    application:
      only: ["Amplenote - Personal - Amplenote", /Amplenote - * - Amplenote/, /*Amplenote*/, crx_pfphkenhllngngioolkalhlmi]
    remap:
      C-p: up
      C-n: down
      C-g: C-o
```

Turned out the above is not matched after checking the log:

`RUST_LOG=debug xremap /home/username/.config/xremap/config.yml`

```
application-client: Sway (supported: true)
application: Chromium
[2022-08-23T03:20:49Z DEBUG xremap::event_handler] 1: KEY_N
[2022-08-23T03:20:49Z DEBUG xremap::event_handler] => 0: KEY_N
```

Is it my regex error? Or matching against application instance or title is not supported? If it's the latter case, is it possible to add support for it? In Sway/i3, the following matching syntax is as follows:

```
for_window [app_id="firefox"] floating enable
for_window [class="Yad" instance="yad"] floating enable
for_window [title="^nomacs.*"] floating enable
```

So that even if `app_id` is not available, we could still use `class` with `instance` or title with regex to match against the target window.

## Environment

```
❯ sway --version
sway version 1.7

❯ xremap --version
xremap 0.7.4
```

Thank you!
