### DISCUSSION TITLE
default key action

### DISCUSSION THREAD

**Discussion by berwynhoyt** [xremap/xremap#591] [Ideas]
Hi Takishi,

Do you think it would be possible to add a default key action that occurs when any other key is pressed? This becomes important, for example, to switch off modes such as {set_mark: false}.

For example, in key maps such as emacs or wordstar, any key that is not defined should turn off marking mode. I can simulate this effect by listing every key on the keyboard as follows, but it seems kludgy:

```
    a: [a, set_mark: false]
    b: [b, set_mark: false]
    c: [c, set_mark: false]
    ... <for every key on the keyboard>
```

I'm thinking this could become:
```
    default: {set_mark: false}
```

Thanks,
Berwyn

**Comment by k0kubun** [comment]
Can you write a full YAML config example that you want to write, not just a part of it?

**Comment by berwynhoyt** [comment]
Sure. Here's a simple example. The last line is the critical bit:
```
virtual_modifiers:
  - CapsLock

keymap:
  - name: Wordstar-Keys
    remap:
      # Cursor
      CapsLock-s: {with_mark: left}
      CapsLock-d: {with_mark: right}
      CapsLock-e: {with_mark: up}
      CapsLock-x: {with_mark: down}
      CapsLock-f: {with_mark: C-right}
      CapsLock-a: {with_mark: C-left}
      CapsLock-r: {with_mark: pageup}
      CapsLock-c: {with_mark: pagedown}

      CapsLock-k:
        remap:
          CapsLock-y: [C-x, {set_mark: false}]
          CapsLock-c: [C-c, {set_mark: false}]  # block copy
          CapsLock-v: [C-v, {set_mark: false}]  # block move
          CapsLock-b: {set_mark: true}
          CapsLock-h: {set_mark: false}
      default: {set_mark: false}

```

**Comment by berwynhoyt** [comment]
I should clarify that for this to work, default action takes place *in addition* to letting the key output its usual key. Perhaps it would be more generally useful to provide the original input key as a special code like so:
```
     default: [{set_mark: false}, _original_key]
```

**Comment by k0kubun** [comment]
Yes, I get it. Just note that `default` should live in a one-level upper indentation because you put it in the place where key names live. But I agree with this general idea.

**Comment by k0kubun** [comment]
The problem I mentioned in my last comment actually confuses me. I think I need extra clarification on what you need. 

Which one did you actually want, is it:

```yml
virtual_modifiers:
  - CapsLock
keymap:
  - name: Wordstar-Keys
    remap:
      # Cursor
      CapsLock-s: {with_mark: left}
      CapsLock-d: {with_mark: right}
      CapsLock-e: {with_mark: up}
      CapsLock-x: {with_mark: down}
      CapsLock-f: {with_mark: C-right}
      CapsLock-a: {with_mark: C-left}
      CapsLock-r: {with_mark: pageup}
      CapsLock-c: {with_mark: pagedown}

      CapsLock-k:
        remap:
          CapsLock-y: [C-x, {set_mark: false}]
          CapsLock-c: [C-c, {set_mark: false}]  # block copy
          CapsLock-v: [C-v, {set_mark: false}]  # block move
          CapsLock-b: {set_mark: true}
          CapsLock-h: {set_mark: false}
    # Unset mark if something not CapsLock-s,d,e,x,f,a,r,c,k is pressed
    default: {set_mark: false}
```

or

```yml
virtual_modifiers:
  - CapsLock
keymap:
  - name: Wordstar-Keys
    remap:
      # Cursor
      CapsLock-s: {with_mark: left}
      CapsLock-d: {with_mark: right}
      CapsLock-e: {with_mark: up}
      CapsLock-x: {with_mark: down}
      CapsLock-f: {with_mark: C-right}
      CapsLock-a: {with_mark: C-left}
      CapsLock-r: {with_mark: pageup}
      CapsLock-c: {with_mark: pagedown}

      CapsLock-k:
        remap:
          CapsLock-y: [C-x, {set_mark: false}]
          CapsLock-c: [C-c, {set_mark: false}]  # block copy
          CapsLock-v: [C-v, {set_mark: false}]  # block move
          CapsLock-b: {set_mark: true}
          CapsLock-h: {set_mark: false}
        # Unset mark if something not CapsLock-y,c,v,b,h is pressed
        default: {set_mark: false}
```

or both?
