### DISCUSSION TITLE
support `mode` feature on `modmap`

### DISCUSSION THREAD

**Discussion by U1s2e3r4n5a6m7e** [xremap/xremap#595] [Ideas]
First of all, thank you for creating this awesome software.

When I tried `remap` Super key to the Left Mouse Button,
```yaml
modmap:
  - name: Super -> Left Mouse Button
    remap:
      LEFTMETA: BTN_LEFT
```
I couldn't use my other remaps in `keymap` related to the Super key:
```yaml
  - remap:
    LEFTMETA-KP8:
      launch: ["cmus-remote", "--volume", "+7%"]
```
I am heavily using mode feature inside keymap and I really like it
```yaml
keymap:
  - mode: Normal
    remap:
      RIGHTALT-L:
        [
          launch:
            ["notify-send", "-u", "critical", "-r", "945", "Xremap MODE", "Launcher mode activated"],
          { set_mode: Launcher },
        ]
  - name: Quick Launch apps
    mode: Launcher
    remap:
      f:
        launch: ["firefox"]
      Esc:
        [
          launch: ["notify-send", "-r", "945", "Xremap MODE", "Back to Normal mode"],
          { set_mode: Normal },
        ]
```
And I was hoping I could also use `mode` feature inside `modmap` but unfortunately it doesn't work. 
```yaml
modmap:
  - mode: InsideModmap
    remap:
      LEFTMETA: BTN_LEFT
      Esc: { set_mode: Normal },

default_mode: Normal
keymap:
  - mode: Normal
    remap:
      LEFTMETA-m: { set_mode: InsideModmap }
```
