### DISCUSSION TITLE
Simulate a held-down key

### DISCUSSION THREAD

**Discussion by musjj** [xremap/xremap#597] [Ideas]
```yaml
KEY_XXX:
  held: [KEY_YYY]
  alone: [KEY_ZZZ]
```

Currently it's not possible to hold down `KEY_ZZZ` using `KEY_XXX`.

In [dual-function-keys](https://gitlab.com/interception/linux/plugins/dual-function-keys), there's an [option](https://gitlab.com/interception/linux/plugins/dual-function-keys#double-tap) that makes this possible. So when you double-tap `KEY_XXX` and hold it, it will act as if `KEY_ZZZ` is being held-down.

Here's an explanation snipped from the readme:

> 
> Tap then press again with `DOUBLE_TAP_MILLIS` (default 150ms) to hold DE.
> 
> ``` text
>                              <-------150ms------->
>                 <---------200ms--------->
> keyboard:       LS↓         LS↑             LS↓               LS↑
> computer sees:  LS↓         LS↑ DE↓ DE↑     DE↓ ..(repeats).. DE↑
> ```
> 
> You can continue double tapping so long as it is within the `DOUBLE_TAP_MILLIS` window.
>

**Comment by k0kubun** [comment]
> when you double-tap KEY_XXX and hold it, it will act as if KEY_ZZZ is being held-down.

Interesting. I would accept a pull request to add such a feature.

Out of curiosity, what do you use the feature for? It's not about keys X, Y, and Z, right?

**Comment by musjj** [comment]
I was using it for my `Enter` mapping:

```yaml
modmap:
  - remap:
      Enter:
        alone:
          - Enter
        held:
          - Alt_L
```

Currently, it's not possible to hold down `Enter` this way. It's not a super big deal, but I'll consider making a PR.
