### DISCUSSION TITLE
xremap OOM

### DISCUSSION THREAD

**Discussion by KAIYOHUGO** [xremap/xremap#600] [Q&A]
I don't know why this happen, and I can not find any log about this. This can be view as a note instead of a bug report because it is too difficult to replicate. I use xremap for 4 month and this never happen before.

![image](https://github.com/k0kubun/xremap/assets/41114603/0c946efb-1bd2-4423-87d6-eb0ac1685556)

![image](https://github.com/k0kubun/xremap/assets/41114603/49d7653d-56d6-414f-aa04-1cecca467a6a)

I think this might cause by my buggy hardware.

**Comment by k0kubun** [comment]
Honestly, no idea. Unless I can reproduce it on my end, I can't investigate it myself. But it'd be nice to note the version, which flavor of xremap you're using, and the config file that produced this issue so that we can find a pattern in case more such issues are reported in the future. Could you share that information?

If it rarely reproduces, I suggest you give it a memory limit and automatically restart it. For example, systemd can do that kind of stuff, and it's useful to manage daemon processes like xremap with such tools anyway.

**Reply by yoshinari-nomura** [reply]
Just a report. 
I met the same situation today: with xremap 0.10.15 installed with "cargo install xremap --features gnome"

```
[332932.965280] [  pid  ]  uid  tgid   total_vm rss      rss_anon  rss_file rss_shmem pgtables_bytes swapents oom_score_adj name
[332932.965720] [ 244907]  1000 244907 50401292 30051264 30050880  384      0         241004544      0        0             xremap
[332932.965954] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=wpa_supplicant.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-wezterm-5282.scope,task=xremap,pid=244907,uid=1000
[332932.965974] Out of memory: Killed process 244907 (xremap) total-vm:201605168kB, anon-rss:120203520kB, file-rss:1536kB, shmem-rss:0kB, UID:1000 pgtables:235356kB oom_score_adj:0
[332937.633802] oom_reaper: reaped process 244907 (xremap), now anon-rss:0kB, file-rss:1536kB, shmem-rss:0kB
```
When editing a large buffer in Emacs, keyboard repeat suddenly wouldn't stop.
I disconnected and reconnected the USB keyboard, then stopped the repeating,
but about a minute later the system froze.

I happened to be logged in from another terminal via SSH and running "top",
which showed xremap rapidly consuming memory. I tried to kill it but it was too late as already become unresponsive.

After leaving it for about 15 minutes, it seems to have recovered thanks to the OOM killer.
OOM killer helped me for the first time :smile:

**Comment by KAIYOHUGO** [comment]
Thank for you reply! I use xremap 0.8.6. And this is my `config.yml`. I use systemd to run xremap but I don't know systemd can set memory limit, thank for the tip!

```yml
modmap:
  - name: Rebind Unrecongized Key
    remap:
      ZOOM: F13
      SLEEP: F14
      SCALE: KEY_TOUCHPAD_TOGGLE
keymap:
  - name: Function Key
    remap:
      SUPER-1: F1
      SUPER-2: F2
      SUPER-3: F3
      SUPER-4: F4
      SUPER-5: F5
      SUPER-6: F6
      SUPER-7: F7
      SUPER-8: F8
      SUPER-9: F9
      SUPER-0: F10
      SUPER-MINUS: F11
      SUPER-EQUAL: F12
  - name: Other
    remap:
      SUPER-C: CAPSLOCK
```
