### DISCUSSION TITLE
[ FEATURE REQUEST ] : Give "modmap" modes

### DISCUSSION THREAD

**Discussion by Tygo-van-den-Hurk** [xremap/xremap#618] [Ideas]
Let's say I use the following config:
```YML

modmap:

  - name: remap
    remap:
      # none

  - name: remap
    remap: 
      KEY_XXX: KEY_YYY

keymap:
  - name: default
    mode: default
    remap:
      KEY_XXX-KEY_ZZZ: { set_mode: other }
      # other remaps...

  - name: other
    mode: other
    remap:
      KEY_XXX-KEY_ZZZ: { set_mode: default }

default_mode: default
```

Then by pressing `KEY_XXX + KEY_ZZZ` I'll be able to turn my keybindings on or off. However, I won't be able to turn the mod map on or off as it does not support modes.

I was wondering if you could add this feature.

**Comment by k0kubun** [comment]
The feature makes sense. Would you like to work on a pull request to add that feature?

**Comment by Tygo-van-den-Hurk** [comment]
I honestly wouldn't have mind, but I don't know how to write rust

**Comment by frflcn** [comment]
Added in v0.10.11

**Reply by zhenhua-wang** [reply]
Thanks for adding this new feature. With this, is it possible to have the MacOS's switching window behavior?

Specifically, when pressed `Super+Tab`, `Super+Grave` will be temporally remapped to `Super+Shift+Tab`, and switch it back when `Super` is released. For example, here is how `keyd` achieves this,

https://github.com/rvaiya/keyd/blob/0cbe717b63c73de7872013b0834d90d802047546/examples/macos.conf#L61-L80

**Reply by frflcn** [reply]
I think what you are looking for is something like this:

```yaml
modmap:
  - 
    name: Switch Windows
    remap: 
      SUPER_L:
        press: { set_mode: cycle }
        release: { set_mode: off }
    
keymap:
  -
    remap:
      GRAVE: SHIFT-TAB
    mode: cycle
```

**Reply by zhenhua-wang** [reply]
Thanks for the reply. This is close, but it also changes the behavior of the Super + Grave key when used alone. When Super + Grave is pressed by itself, it should switch between windows of the current application. However, when Super + Tab is pressed, only the Tab key should be released while holding down the Super key—during this time, the Grave key should be temporarily remapped to Shift + Tab. 

I tried this, but it seems that press/release is not yet supported in keymap. Any idea on this? Thanks.
```
keymap:
  - name: Apple Switch
    remap:
      Super-tab:
        press: [Super-tab, { set_mode: cycle }]
        release: { set_mode: off }

  - name: Switch_Windows
    remap:
      GRAVE: shift-tab
    mode: cycle
```

**Reply by frflcn** [reply]
Ok I think I see what you need now. Try this out and let me know if it works.

```yaml
modmap:
  - 
    name: I'm always on
    remap: 
      SUPER_L:
        press: { set_mode: ready }
        release: { set_mode: default }
  -
    name: Ready for Anything
    remap:
      TAB:
        press: { set_mode: cycle }
        release:
    mode: ready
    
keymap:
  -
    name: Switching Between All Windows
    remap:
      GRAVE: SHIFT-TAB
    mode: cycle
```

**Reply by zhenhua-wang** [reply]
Thanks for sharing. This works great! I have one last question: is it possible to achieve the above while also remapping to another key?

For example, I've remapped ALT to SUPER. I’d like to use the remapped SUPER (ALT on physical keyboard) to trigger the same effect. However, it seems that the previous remap is overriding this 'switching window' behavior.
```
  - name: mac keyboard
    remap:
      # Swap left Super with left Alt
      LEFTMETA: LEFTALT
      LEFTALT: LEFTMETA

  - name: I'm always on
    remap:
      LEFTMETA:
        press: { set_mode: ready }
        release: { set_mode: default }

  - name: Ready for Anything
    remap:
      TAB:
        press: { set_mode: cycle }
        release:
    mode: ready
```

I also tried remap and set_mode at the same time, but it does not seems to work.
```
  - name: I'm always on
    remap:
      LEFTALT:
        press: [LEFTMETA, { set_mode: ready }]
        release: { set_mode: default }
```
