### DISCUSSION TITLE
Different command on repeated button press

### DISCUSSION THREAD

**Discussion by toby63** [xremap/xremap#619] [Q&A]
Hello,

I use the following config now, for enabling push-to-talk in Mumble:

``` 
modmap:
    - name: Mumble1
      remap:
        PAGEDOWN:
          skip_key_event: true
          press: { launch: ["mumble", "rpc", "starttalking"] } 
          release: { launch: ["mumble", "rpc", "stoptalking"] } 
```

Everything is working well, but I would also like to have a different command that would look something like this:
``` 
    { launch: ["mumble", "rpc", "starttalking"] } 
     repeat: { launch: ["mumble", "rpc", "stoptalking"] } 
```

The idea is:
1. press a button (PAGEDOWN in my case) to starttalking
2. press the same button again to stoptalking
3. press the same button again to starttalking again and so on

How can I do that?
And if it isn't possible yet, consider it a Feature Request.

**Comment by k0kubun** [comment]
I'm not sure if I follow. With:

```yml
modmap:
  - remap:
      PAGEDOWN:
        skip_key_event: true
        press: { launch: ["mumble", "rpc", "starttalking"] } 
        repeatedpress: { launch: ["mumble", "rpc", "stoptalking"] } 
```

what happens when you `release` without `repeatedpress`? Do you want to make `release` an optional config and emit no event on it? To avoid confusion, could we always use a complete YAML config file in each snippet going forward?

Also, I'm not sure how this config achieves "2. press the same button again to stoptalking". If you tap the button twice and issue `press` event twice, nothing seems to trigger `stoptalking` with this config, which is why I raised the above question.

**Comment by toby63** [comment]
@k0kubun Sry for the confusion, ignore the "press" stuff, I did not think correctly about it (that press means "keep pressing").

What I want to achieve is what I have written below that:
1. click a button (PAGEDOWN in my case) to starttalking
   - for clarification: You don't keep pressing, but starttalking stays activated.
3. click the same button again to stoptalking
4. click the same button again to starttalking again and so on

**Comment by k0kubun** [comment]
and what's an example YAML file you want to use for it?

**Comment by toby63** [comment]
@k0kubun 

I think it could be something like this:
``` 
modmap:
    - name: Mumble1
      remap:
        PAGEDOWN:
          skip_key_event: true
          click: { launch: ["mumble", "rpc", "starttalking"] } 
          repeat: { launch: ["mumble", "rpc", "stoptalking"] } 
``` 

Or this:

``` 
modmap:
    - name: Mumble1
      remap:
        PAGEDOWN:
          skip_key_event: true
          launch: ["mumble", "rpc", "starttalking"]   # I don't know if it works like this
          repeat: { launch: ["mumble", "rpc", "stoptalking"] } 
```

**Comment by k0kubun** [comment]
I still don't follow how your YAML achieves what you described. (1) is fine, yes. (2) doesn't make sense because `stoptalking` is implemented under `repeat`, which is not a "click". Then you proceed to do the same thing as (2) to trigger the other command, `starttalking`, so I'm not sure which action you meant by "click the same button", `click` or `repeat`.

Based on what you described, isn't this what you need? It doesn't seem like a new feature to me.

```yml
keymap:
  - remap:
      PageDown:
        - { launch: ["mumble", "rpc", "starttalking"] }
        - { set_mode: started }
    mode: stopped
  - remap:
      PageDown:
        - { launch: ["mumble", "rpc", "stoptalking"] }
        - { set_mode: stopped }
    mode: started
default_mode: stopped
```
