### DISCUSSION TITLE
Can Caps Lock be used both as the Esc key(single press-release) and as a virtual modifier?

### DISCUSSION THREAD

**Discussion by marsjane** [xremap/xremap#626] [Q&A]
I use Capslock as virtual-modifiers and it works fine, then I tried to also map it to Esc in modmap, but it seems the virtual-modifiers behaviour of Capslock would then be ineffective. Is there any advice on this?

**Comment by dpc** [comment]
```
> cat ~/.config/xremap/config.yml
modmap:
  - name: CapsLock to RightCtrl/Esc
    remap:
      CapsLock:
        held: Ctrl_R
        alone: Esc
        alone_timeout_millis: 200

keymap:
  - name: RightCtrl+hjkl to Arrows
    remap:
      Ctrl_R-h: Left
      Ctrl_R-l: Right
      Ctrl_R-j: Down
      Ctrl_R-k: Up
  - name: RightCtrl + Esc to "~ and `"
    remap:
      Ctrl_R-Esc: Grave
      Ctrl_R-S-Esc: S-Grave
      Ctrl_R-Grave: Grave
      Ctrl_R-S-Grave: S-Grave

  - name: RightCtrl + n to Fn"
    remap:
      Ctrl_R-1: F1
      Ctrl_R-2: F2
      Ctrl_R-3: F3
      Ctrl_R-4: F4
      Ctrl_R-5: F5
      Ctrl_R-6: F6
      Ctrl_R-7: F7
      Ctrl_R-8: F8
      Ctrl_R-9: F9
      Ctrl_R-0: F10
      Ctrl_R-Minus: F11
      Ctrl_R-Equal: F12

  - name: RightCtrl + other
    remap:
      Ctrl_R-P: KEY_PRINT
```

**Comment by dpc** [comment]
For some reason the above stopped working, and holding CapsLock gave me just Ctrl.

I've switched to just using `CapsLock` as modifier:

```
virtual_modifiers:
  - CapsLock
modmap:
  - name: CapsLock to RightCtrl/Esc
    remap:
      CapsLock:
        held: CapsLock
        alone: Esc
        alone_timeout_millis: 200

keymap:
  - name: RightCtrl+hjkl to Arrows
    remap:
      CapsLock-h: Left
      CapsLock-l: Right
      CapsLock-j: Down
      CapsLock-k: Up
  - name: RightCtrl + Esc to "~ and `"
    remap:
      CapsLock-Esc: Grave
      CapsLock-S-Esc: S-Grave
      CapsLock-Grave: Grave
      CapsLock-S-Grave: S-Grave

  - name: RightCtrl + n to Fn"
    remap:
      CapsLock-1: F1
      CapsLock-2: F2
      CapsLock-3: F3
      CapsLock-4: F4
      CapsLock-5: F5
      CapsLock-6: F6
      CapsLock-7: F7
      CapsLock-8: F8
      CapsLock-9: F9
      CapsLock-0: F10
      CapsLock-Minus: F11
      CapsLock-Equal: F12

  - name: RightCtrl + other
    remap:
      CapsLock-P: KEY_PRINT
```
