### DISCUSSION TITLE
XReMap don't work in Manjaro (Arch Linux) with DKE 6 with Wayland (no device listed)

### DISCUSSION THREAD

**Discussion by GabrielFrigo4** [xremap/xremap#628] [Q&A]
## About
The title is quite explanatory, but I will provide more details:

### default.yml
``` yaml
modmap:
  - name: Default ReMap
    remap:
        KEY_COMPOSE: KEY_RO
        KEY_RO: CTRL_R
    device:
        only: '/dev/input/event0'
```

### input
```zsh
xremap default.yml
```

### output
```
Selecting devices from the following list:                                                                                                            
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
Error: Failed to prepare input devices: No device was selected!
```

##  System Info
 - __OS__ => `Manjaro`
 - __Desktop Environments__ => `DKE 6`
 - __Window System__ => `Wayland`
 - __Package__=> `aur/xremap-kde-bin`

**Comment by ahsbjunior** [comment]
Hi, I have the same problem here.  But I'm using Fedora.

- OS => Fedora
- Desktop Environments => KDE 6
- Window System => Wayland
- Package=> [Fedora Copr](https://copr.fedorainfracloud.org/coprs/blakegardner/xremap/)

### config.yml
```
modmap:

keymap:
  - name: Control Home
    remap:
      # home e end
      ALT-LEFT: home
      ALT-RIGHT: end
```
