### DISCUSSION TITLE
Question: How to assign different remap for key pressed alone and key combo

### DISCUSSION THREAD

**Discussion by vuongtuha** [xremap/xremap#630] [Q&A]
I'm trying to make Capslock key as a Compose key. My target:
 - If key Capslock pressed alone, and released, it works as Space
 - If key Capslock pressed, and held, it works as normal toggle Capslock mode
 - If key Capslock pressed, held, and combine with other key, it works like second Ctrl mode
 
Here's my temp config to test this work:
```
modmap:
  - name: Key alone
    remap:
      KEY_CAPSLOCK:
        held: Capslock
        alone: Space
        alone_timeout_millis: 1000
  - name: Mouse bkwd
    remap:
      BTN_SIDE: BTN_EXTRA
      BTN_EXTRA: BTN_SIDE
virtual_modifiers:
  - CapsLock
keymap:
  - name: Key compose
    remap:
      CapsLock-a: left
      CapsLock-d: right
      CapsLock-w: up
      CapsLock-s: down
```
There're some misbehaviour than expected:
- Key CapsLock held do not work as normal CapsLock
- Key combine randomly not working if you delay press 2nd key. In example, on terminal, CapsLock-a navigate normally for the 1st time. You wait little bit, genuine guess longer than held time, then CapsLock-a show [a] character 
- Key combine stop repeated behaviour if i held both keys. I can do that if key CapsLock wasn't remapped by modmap

I think my reuest is little clunky for most normal usage. Just wonder if it's possible and i made mistake on config myself, hope that so.
