### DISCUSSION TITLE
how to use three keys with a modifier in keymaps

### DISCUSSION THREAD

**Discussion by Aneeqasif** [xremap/xremap#632] [Q&A]
i have following config that bind alt-r to c-semicolon all i want is to bind C-simicolon-j to triger Down key but all the things that i have tried have not worked

```yaml
keymap:
- name: Aremap
  remap:
    super-d:
      remap:
        f:
          launch: ["firefox"]
        b:
          launch: ["brave"]
    KatakanaHiragana: [C-semicolon]
    KatakanaHiragana-j: Down


modmap:
- name: Global modemaps
  remap:
    capslock:
      alone: esc
      alone_timeout_millis: 200
      held: leftctrl
    esc: reserved

- name: right alt in pycharm
  application:
  remap:
    ALT_R : KatakanaHiragana
```

**Comment by BlakeGardner** [comment]
@Aneeqasif below is my example of binding a two key press to a three key press combo in an application specific way

```yml
  - name: Terminals
    application:
      only: [gnome-terminal-server, tilix, org.gnome.Ptyxis]
    remap:
      RIGHTCTRL-t: ctrl-shift-t
```
