### DISCUSSION TITLE
Firefox browser input box cannot launch button

### DISCUSSION THREAD

**Discussion by mochouaaaaa** [xremap/xremap#637] [Q&A]
<details>
<summary>terminal output</summary>

```text
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : Power Button
/dev/input/event1 : Power Button
/dev/input/event10: HDA NVidia HDMI/DP,pcm=7
/dev/input/event11: HDA NVidia HDMI/DP,pcm=8
/dev/input/event12: HDA NVidia HDMI/DP,pcm=9
/dev/input/event13: HD-Audio Generic Rear Mic
/dev/input/event14: HD-Audio Generic Front Mic
/dev/input/event15: HD-Audio Generic Line
/dev/input/event16: HD-Audio Generic Line Out Front
/dev/input/event17: HD-Audio Generic Line Out Surround
/dev/input/event18: HD-Audio Generic Line Out CLFE
/dev/input/event19: HD-Audio Generic Front Headphone
/dev/input/event2 : ASUS ROG Gladius II
/dev/input/event20: mochou的🎧 (AVRCP)
/dev/input/event3 : ASUS ROG Gladius II Keyboard
/dev/input/event4 : A87 Keyboard
/dev/input/event6 : Smart Smart Wireless Device
/dev/input/event7 : Smart Smart Wireless Device
/dev/input/event8 : Eee PC WMI hotkeys
/dev/input/event9 : HDA NVidia HDMI/DP,pcm=3
------------------------------------------------------------------------------
Selected keyboards automatically since --device optionsweren't specified:
------------------------------------------------------------------------------
/dev/input/event3 : ASUS ROG Gladius II Keyboard
/dev/input/event4 : A87 Keyboard
/dev/input/event6 : Smart Smart Wireless Device
------------------------------------------------------------------------------
application-client: wlroots (supported: true)
application: firefox
```
</details>

- xremap config
```yml
# modmap:
#   - name: Replace ctrl with Command
#     application:
#       not: kitty
#     remap:
#       KEY_LEFTMETA: KEY_LEFTCTRL

keymap:
  - name: Replace CTRL with Command
    application:
      not: [kitty, hyprland]
    remap:
      SUPER-w: C-w
      SUPER-c: C-c
      SUPER-v: C-v
      SUPER-x: C-x
      SUPER-a: C-a
      SUPER-t: C-t
      SUPER-f: C-f
```

Problem: The keys work fine in Google Chrome and also work in Firefox, but when focus is on the input box in Firefox, the keys have no effect.
