### DISCUSSION TITLE
Prevent double-type works, but not perfectly

### DISCUSSION THREAD

**Discussion by berwynhoyt** [xremap/xremap#639] [Ideas]
My spacebar frequently 'bounces' emitting two spaces. It's maddening. Perhaps a feature of how I type because it's now happened to me on two separate laptop keyboards. I'd love a way to prevent this without switching on bouncekeys, which creates other problems (cf. #563).

This solves the problem:
```
keymap:
  - name: prevent spacebar bounce from emitting two spaces
    remap:
      space:
        remap:
          space: null
        timeout_key: space
        timeout_millis: 150
```

This works already, and makes use of timeout_key (documented in #128) and recently merged `null` action (documented in #544). Neither of these are documented in the README, so I will create a PR to add these soon.

Although the above does work, it isn't perfect because now the space always comes out 150ms after pressing the spacebar, which is a noticable delay. Is it possible to do this instead:
```
keymap:
  - name: prevent spacebar bounce from emitting two spaces
    remap:
      space:
        press: space
        remap:
          space: null
        timeout_key: null
        timeout_millis: 150
```
Note the addition of `press: space` which is currently only supported for modmap, not keymap. I envisage that it will do the same as remap `space: space` except that it will also allow the following timed and nested remap, which prevents bounce. Note also the change of timeout_key to `null` which prevents output of an additional space (since one was already put out immediately when space was pressed).

I'm asking two questions:
- Is there already a way that I'm unawareof to specify this `press: space` and still nest the remap?
- If not, would someone consider adding this? Perhaps @wistoft or @kokubun? I do not know rust myself.
