### DISCUSSION TITLE
Binding middle mouse button - aka mouse wheel emulation support

### DISCUSSION THREAD

**Discussion by Felipe-9** [xremap/xremap#644] [Q&A]
Hello so im having some trouble with the mouse wheel being very jumpy so i wanted to do a workaround to fix the issue.
my idea is to bind the middle mouse button so that when its held, the mouse movement x and y becomes scroll horizontal and vertical, its basically a drag like behavior.

for reference some important keys:
- BTN_MIDDLE: is the middle mouse button
- REL_{X/Y}: is the {Horizontal/vertical} scroll

searching a bit i figured out three hypothesis how to do this (all to which i couldnt accomplish)

## firstly 
would be to set a custom modifier to which middle mouse button will set when held and unset when released, the modifier would make so that mouse move would map to scroll behaviour this is what i tried for this one:
```yaml
keymap:
- name: Middle mouse drag
  remap:
    MOUSE_DRAG-REL_Y: REL_WHELL
    MOUSE_DRAG-REL_x: REL_HWHELL
modmap:
- name: 'Middle mouse drag: setting modifier'
  remap:
    BTN_MIDDLE:
      alone_timeout_millis: 150
      held:
        set_modifier: MOUSE_DRAG
      release:
        unset_modifier: MOUSE_DRAG
virtual_modifiers:
- MOUSE_DRAG
```

## second
would be to instead of creating a new modifier use "KEY_RIGHTALT" instead
## third 
would be to use mouse middle as the modifier itself, but without loosing the middle-mouse click behaviour
for the third i tried this:
```yaml
keymap:
- name: Middle mouse drag
  remap:
    BTN_MIDDLE-REL_Y: REL_WHELL
    BTN_MIDDLE-REL_x: REL_HWHELL
modmap: []
virtual_modifiers:
- BTN_MIDDLE
```

## errors
for now the main error is the following
```
keymap[0].remap: unknown key 'REL_Y' at line 4 column 5
```
clearly its not understanding REL_Y as a button, yet its the event to which appears when using `evtest` what should i do instead?
please help
