### DISCUSSION TITLE
Normal key as virtual modifier when held

### DISCUSSION THREAD

**Discussion by nilehmann** [xremap/xremap#645] [Q&A] [answered]
I want to use `apostrophe` (the `'` key) as a virtual modifier but act normally on tap. I have the current workaround that maps `apostrophe` to a different key only on held and then adds the other key as the virtual modifier.

```yaml
virtual_modifiers:
 - hangeul
modmap:
  - apostrophe:
        held: hangeul
        alone: apostrophe
```

This works great, except that when I do `shift-apostrophe` (to write `"`), I tend to release `shift` before I release `apostrophe`, which ends up treating `apostrophe` as a modifier key. I would like `shift-apostrophe` to always result in `"` no matter which key I release first.

Is there a different way to achieve what I want or a way to specify the behavior of `shift-apostrophe`?

Thanks!!

**Comment by nilehmann** [comment, marked as answer]
Oh I figure it out! I can also make `shift` have a different behavior on tap. This is my final configuration

```yaml
virtual_modifiers:
 - hangeul
modmap:
  - remap:
      Apostrophe:
        held: Hangeul
        alone: Apostrophe
      LeftShift:
        held: LeftShift
        alone: muhenkan
keymap:
  - remap:
      Hangeul-muhenkan: Shift-apostrophe
```

Sometimes you just need rubberducking :)
