### DISCUSSION TITLE
modmap: invalid type: map

### DISCUSSION THREAD

**Discussion by MoltenMonster** [xremap/xremap#647] [Q&A]
I installed xremap on Fedora with https://github.com/BlakeGardner/xremap-fedora, following those instructions. When I do `xremap config.yml`, I get this error: `Error: Failed to load config 'config.yml': modmap: invalid type: map, expected a sequence at line 2 column 5`.

```yml
modmap:
    remap:
      capslock: esc
      leftshift: capslock
      Leftmeta: LeftCtrl
      rightmeta: leftshift
      rightalt: leftmeta
keymap:
    remap:
      SUPER-h: left
      SUPER-j: down
      SUPER-k: up
      SUPER-l: right
      M-SUPER-H: C-pageup
      M-SUPER-L: C-pagedown
      C-SUPER-H: C-[
      C-SUPER-L: C-]
```

**Comment by nilehmann** [comment]
Both `modmap` and `keymap` expect a list (a sequence), your file should look like so

```yaml
modmap:
  - remap:
      capslock: esc
      leftshift: capsloc
      Leftmeta: LeftCtrl
      rightmeta: leftshift
      rightalt: leftmeta
keymap:
  - remap:
      SUPER-h: left
      SUPER-j: down
      SUPER-k: up
      SUPER-l: right
      M-SUPER-H: C-pageup
      M-SUPER-L: C-pagedown
      C-SUPER-H: C-[
      C-SUPER-L: C-]
```
