### DISCUSSION TITLE
Remap "Ctrl + Shift + C" key in Ubuntu

### DISCUSSION THREAD

**Discussion by devstefancho** [xremap/xremap#655] [Q&A] [answered]
Hi, I want to remap copy and paste keymap in Ubuntu 24.04
but it didn't work.. ( I tested Alt-h key, and it worked)
how can i remap `ctrl + shift + c` to `alt_left + c`?

```yaml
modmap:
  - name: capslock to control
    remap:
      CapsLock: Control_L

keymap:
  - name: Terminal
    application:
      only: [Gnome-terminal]
    remap:
      Alt-h: left # work
      Alt-v: [C-left, Shift-left, v] # 1. not work
      Alt-v: C-S-v # 2. not work
      Alt-v: S-C-v # 3. not work
```

**Comment by devstefancho** [comment, marked as answer]
I read document again, and I found that i should use not "S" but "Shift"
now it works

```yaml
keymap:
  - name: Terminal
    application:
      only: [Gnome-terminal]
    remap:
      Alt-h: left # work
      Alt-c: C-Shift-c
      Alt-v: C-Shift-v
```
