### DISCUSSION TITLE
KEY_ENTER not working or repeated

### DISCUSSION THREAD

**Discussion by calvinkatz** [xremap/xremap#657] [Q&A]
Hello,

I'm encountering an issue where the ENTER key is not working as expected when running xremap.

KDE 6 Wayland
xremap v0.10.8

## Steps to Reproduce:

Use the following configuration:

```yaml
keymap:
  - name: FF14
    remap:
      SHIFT-XHIRES_UPSCROLL: SHIFT-KEY_PAGEUP
      SHIFT-XHIRES_DOWNSCROLL: SHIFT-KEY_PAGEDOWN
      SHIFT-XUPSCROLL: SHIFT-KEY_PAGEUP
      SHIFT-XDOWNSCROLL: SHIFT-KEY_PAGEDOWN
    application:
      only: ffxiv_dx11.exe
    device:
      only:
        - 'Nordic Semiconductor USB  Gaming Mouse'
        - 'coseyfannitutti DISCIPLINE'
```

Start xremap with debug:

```bash
RUST_LOG=debug xremap ~/config.yml
```

Use one of the configured hotkeys and then switch to FF14 window.

## Result

The remapped keys work as expected, SHIFT+WHEELUP/DOWN = SHIFT+PAGEUP/DOWN.
The enter key no longer works as expected.

## Additional Information

On initial start of xremap the terminal is spammed with newlines but no KEY_ENTER displays in the log. After activating one of the configured hotkeys and then switching to FF14 window the newlines will stop.

After switching to FF14 the enter key no longer works. Pressing enter key does nothing in any window until I kill xremap. Sometimes after switching to FF14 enter will still repeatedly input to only FF14.
These repeated enter inputs aren't registered in the debug log, but keyboard enter presses are.

**Comment by bbenne10** [comment]
I think the reproduction case can be simplified in some cases. It is not clear why but this reproduces it for me:

```
modmap:
   - name: capslock to f13
     remap:
       CAPSLOCK: f13
```

Starting with `xremap <saved path>` will cause newlines to seemingly infinitely be spit out to the terminal. 

I initially thought this had something to do with device enumeration because I had some success in avoiding the issue when specifying the device to remap. I think that this success was because I had an external keyboard hooked up and was only modifying the internal device (limited with the `--device` flag). Trying again with only the internal keyboard attached, I now believe that this is related to receiving inputs on the device being remapped when starting the daemon, as this (coupled with not touching the keyboard for 1 second) works: `sleep 1 & xremap <saved path>`. I think this makes this a duplicate of https://github.com/xremap/xremap/discussions/592
