### DISCUSSION TITLE
Questions from a potential future user & contributor

### DISCUSSION THREAD

**Discussion by kermitfrog** [xremap/xremap#667] [Ideas]
Hi, 
I'm considering to move from my aged own tool (inputMangler) to xremap. 
This comes with some questions about the current code and future features.

I decided to put this in the 'Ideas' section, because this post is mostly development related while 'Q&A' seemed more for usage questions that can be answered by the community.

---

In part of my converted configuration I have:
```
modmap:
[..]
# global default for mouse
 - name: ''
   remap:
     BTN_RIGHT: BTN_EXTRA
     BTN_MIDDLE: BTN_RIGHT
     BTN_EXTRA: BTN_MIDDLE
[..]
# modmap for yakuake
 - name: ''
   remap:
     BTN_MIDDLE: BTN_RIGHT
     BTN_EXTRA: BTN_MIDDLE   
   application:
     only:                
     - org.kde.yakuake   
[..]
keymap:
# keymap for yakuake
 -name: ''
  remap:
  # BTN_RIGHT has to be changed to BTN_EXTRA to work
    BTN_RIGHT:
    - ALT-SHIFT-KEY_PAGEDOWN
  application:
    only:                
    - org.kde.yakuake
[..]
```
I noticed, that to remap (what the manufacturer sees as) BTN_RIGHT in the 'remap' section, I need to use the globally remapped keycode (BTN_EXTRA). Is this intentional or a bug?

---

If I correctly understand the code of `fn on_key_event()` in `event_handler.rs`, it calls the methods `find_modmap()` and sometimes `find_keymap()` on every incoming event. These functions then do multiple map lookups. This seems very inefficient to me. Is there a reason it has to be done this way, instead of having variables for current mappings and updating them when the current window changes? 

---

There are some features that my own tool has, that I would like to add to xremap (if I settle on it):
 - Device matching by vendor/product ids.
 - Device matching by phys path.
 - Wheel acceleration, that is: if you scroll the mouse wheel multiple times in a certain timeframe, it will add additional events to speed up scrolling. Admittedly, in inputMangler this does not work as well as I want it to.
 - Autofire -- repeated events when key is held.
 - More complex macros, including support for different events, depending on the value of the event. e.g. type "Hello" on keypress and "world" on release. Also support for custom timeouts between generated events.
 
And some that inputMangler does not have:
 - A GUI -- this would be the first thing on my list. Note that my vision of a GUI uses a different organizational logic from xremap - more similiar to what I did in inputMangler. While it can be translated, it would make more sense to have a separate config, from which the xremap configuration is generated.
 - Multiple subconfigurations for an application that can be activated depending on internal variables. These variables could be changed by shortcuts.

The big question is: do these features align with your goals for xremap, or are there conflicts?

One challenge that I see is the configuration format. It seems to be engineered towards convenience when configuring the application by text editor (as long as you're using the us-layout). But this has a disadvantage: new features need new syntax, which increases the complexity much more than with a format that is optimized for a GUI.
I'm not sure how much I can add without either making the code hard to maintain or break compatibility with older configuration files.
