### DISCUSSION TITLE
Defect: Output with synthetic modifiers break for all apps that read raw keyboard input

### DISCUSSION THREAD

**Discussion by tecfu** [xremap/xremap#669] [Q&A]
Example:

```
keymap:
  - name: "Spacebar Mapping Sequences"
    remap:
      KEY_SPACE:
        remap:
          KEY_SEMICOLON: [SHIFT-KEY_4]
        timeout_millis: 100
```

In Alacritty, this results in `4`. In Chrome, you will see a `$`

Suggested fix: 

Refactor to support first-class raw string output (NOT CURRENTLY SUPPORTED), i.e.:

```
keymap:
  - name: "Spacebar Mapping Sequences"
    remap:
      KEY_SPACE:
        remap:
          KEY_SEMICOLON: "$"
        timeout_millis: 100
```
