### DISCUSSION TITLE
`application:` and `window:` filters not working when `xremap` is launched from Sway config

### DISCUSSION THREAD

**Discussion by Kabouik** [xremap/xremap#672] [Q&A]
The following configuration works fine when I run it from a terminal in my Sway session using `xremap ~/.config/xremap/config.yml`, including the `Application:` section and its associated `not:` section

```yaml
keymap:
  # - name: Lunar special keys
  #   remap:
  - name: Lunar-specific
    remap:
      M-p: Print
      C-M-p: C-Print
      Shift-M-p: Shift-Print
  - name: Emacs-like keybindings system-wide
    application:
      not: [emacs, emacsclient, foot, footclient]
    window:
      not: [/nano/, /emacs/, /emacsclient/]
    remap:
      # Forward/Backward word
      M-b: { with_mark: C-left }
      M-f: { with_mark: C-right }
      # Beginning/End of line
      C-a: { with_mark: home }
      C-e: { with_mark: end }
      # Page up/down
      M-v: { with_mark: pageup }
      C-v: { with_mark: pagedown }
      # Beginning/End of file
      M-Shift-comma: { with_mark: C-home }
      M-Shift-dot: { with_mark: C-end }
      # Newline
      C-m: enter
      C-j: enter
      C-o: [enter, left]
      # Copy
      C-w: [C-x, { set_mark: false }]
      M-w: [C-c, { set_mark: false }]
      C-y: [C-v, { set_mark: false }]
      # Delete
      C-d: [delete, { set_mark: false }]
      M-d: [C-delete, { set_mark: false }]
      # Kill line
      C-k: [Shift-end, C-x, { set_mark: false }]
      # Kill word backward
      Alt-backspace: [C-backspace, {set_mark: false}]
      # set mark next word continuously.
      C-M-space: [C-Shift-right, {set_mark: true}]
      # Undo
      C-slash: [C-z, { set_mark: false }]
      C-Shift-ro: C-z
      # Mark
      C-space: { set_mark: true }
      # Search
      C-s: C-f
      # C-r: Shift-F3
      M-Shift-5: C-h
      # Cancel
      C-g: [esc, { set_mark: false }]
      # App launcher *using sway-launcher-desktop configured in Sway here)
      M-x: Super-m
      # C-x YYY
      C-x:
        remap:
          # C-x h (select all)
          h: [C-home, C-a, { set_mark: true }]
          # C-x C-f (open)
          C-f: C-o
          # C-x C-s (save)
          C-s: C-s
          # C-x k (kill tab)
          k: C-f4
          # C-x C-c (exit)
          C-c: C-q
          # C-x u (undo)
          u: [C-z, { set_mark: false }]
          # C-x b (select buffer; used to select window using sway-window-switcher configured in Sway here)
          b: Super-Tab
          C-b: C-Shift-a
```

However, if I run it automatically when Sway opens using `exec_always sudo "$(realpath $(which xremap))" /home/mat/.config/xremap/config.yml` in my Sway config, then it works in every application and window, the `not:` filters no longer work. `swaymsg -t get_tree` does return the same windows and applications as in the above case.

`xremap` is whitelisted in my `/etc/sudoers` file so Sway has no trouble running it without a password prompt.
