### DISCUSSION TITLE
Keymap still applies on Alacritty even with application: not: Alacritty.Alacritty

### DISCUSSION THREAD

**Discussion by shaaaatu** [xremap/xremap#674] [Q&A]
I'm trying to disable keymaps on Alacritty by using `application: not`, but it does not seem to work as expected.

Here are the details:
If I write `application: not: Alacritty.Alacritty`, the keymap will work on every application include Alacritty.
If I write `application: only: Alacritty.Alacritty`, the keymap will not work on every application include Alacritty.
The application name (`Alacritty.Alacritty`) was confirmed using `$ wmctrl -x -l`.

I installed xremap from AUR and tried without sudo which has written in readme at first.
And this problem occurred, so I tried `cargo install xremap --features x11`. Then I removed udev rule from `/etc/udev/rules.d/99-input.rules` and then run with sudo(I also did `xhost +SI:localuser:root` even I didn't get `No protocol specified`).
But still same.

I also get this error when I run with sudo.
`GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
application-client: GNOME (supported: false)`

Without sudo, I got same error but I fixed with this one
https://github.com/xremap/xremap/discussions/588

Here is my environment:
OS: Arch Linux
Desktop environment: i3wm
Display server: X11
xremap version: 0.10.9
rust version: rustc 1.86.0

```
modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L

keymap:
  - name: readline like keymap except terminal
    application:
      not: Alacritty.Alacritty
    remap:
      C-h: backspace
      C-e: end
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-d: delete
      C-leftbrace: Esc
```
