### DISCUSSION TITLE
New feature "press/repeat/release" does not work well together with kepmap

### DISCUSSION THREAD

**Discussion by zhenhua-wang** [xremap/xremap#687] [Q&A]
Hi, I'm encountering an issue with the new `press/repeat/release` feature in Modmap.

It seems that this new feature in `modmap` does not work well with `keymap`. For example, if I remap `Super-v` to `C-v` in `keymap` and `LEFTALT` to `LEFTMETA` in `modmap` using `press/repeat/release`, press `Super-v` (`LEFTALT+v` on physical keyboard) still sends `Super-v` rather than `C-v`.

I'm using the latest version on cargo (xremap on AUR is outdated) and I've tried both Gnome X11 and wayland in Arch Linux. All have this issue.

Here is a minimal config that can reproduce this:
```
modmap:
  - name: Except Mac Keyboard
    remap:
      # Swap left Super with left Alt
      LEFTMETA: LEFTALT
      LEFTALT:
        skip_key_event: true
        press: [{ press: LEFTMETA }, { set_mode: mac_tab }]
        repeat: { repeat: LEFTMETA }
        release: [{ release: LEFTMETA }, { set_mode: default }]
    device:
      not: ['Apple Inc. Magic Keyboard']

  - name: Mac Tab
    remap:
      TAB:
        press: { set_mode: cycle }
        release:
    mode: mac_tab

keymap:
  - name: Switch Windows
    remap:
      GRAVE: shift-tab
    mode: cycle

  - name: Apple keymap
    remap:
      Super-v: C-v
```
