### DISCUSSION TITLE
Can't seem to set up Shift+CapsLock -> Capslock

### DISCUSSION THREAD

**Discussion by Dillongc21** [xremap/xremap#689] [Q&A]
Hi there! 

Just started using xremap so I may be doing something that should be obvious, but I can't seem to set things up so that CapsLock is my Escape key, but holding Shift while pressing CapsLock will activate CapsLock. I thought this would be relatively straightforward and wrote the following config:

```yaml
modmap:
  - name: Global
    remap:
      # CapsLock -> Esc
      CapsLock: Esc

keymap:
  - name: Global
    remap:
      # Shift + CapsLock -> CapsLock
      Shift-CapsLock: CapsLock
```
The CapsLock to Esc works fine, but the Shift+Capslock is not. I have it set up to just swap Caps and Esc at the moment, but anyone know how I can implement what I originally wanted? Thanks in advance!

**Comment by gevious** [comment]
You could try something like this
```
modmap:
  - name: Global
    remap:
      CapsLock: 
          held: Esc
          alone: CapsLock
          alone_timeout: 50
```
