### DISCUSSION TITLE
capslock binding times out after 1 second for some keys

### DISCUSSION THREAD

**Discussion by gevious** [xremap/xremap#692] [Q&A]
I have a simple `xremap` config, to map CapsLock to Ctrl_R (below). When I'm in the terminal, I've noticed that `CapsLock-n` (to scroll down) works all the time but something like `CapsLock-p` (to scroll up) will stop working after a 1 second. Then I need to release the `CapsLock` key, and then it will work again for a little bit. When I use the `Ctrl` key instead of `CapsLock`, I don't have this issue.

I'm confused why some keybindings are affected and not others? FWIW, I'm using Wayland
```
modmap:
  - name: CapsLock to RightCtrl/Esc
    remap:
      CapsLock: 
        held: Ctrl_R
        alone: Esc
        alone_timeout: 200
```
