### DISCUSSION TITLE
How to trigger key remap when hold 2 keys at the same time?

### DISCUSSION THREAD

**Discussion by vuongtuha** [xremap/xremap#698] [Q&A] [answered]
I wanna hold BTN_LEFT + BTN_RIGHT in mouse then remap it to Super key. No matter what is 1st. Is that in support feature?

**Comment by hpccc53** [comment, marked as answer]
I assume that you are thinking that they should be pressed simultaneously (in any order), within some delay. But I can't see a way to do that.

A similar way is possible, though. Here you must press left button first and then right button. The drawback is that the left button click is still emitted, but there is no need for timeout.

```yml
default_mode: both_mouse_buttons_unpressed

modmap:
  - mode: both_mouse_buttons_unpressed
    remap:
      btn_left:
        press: { set_mode: left_button_pressed }

  - mode: left_button_pressed
    remap:
      btn_left:
        release: { set_mode: both_mouse_buttons_unpressed }
      btn_right:
        press: [{ press: w_l }, { set_mode: w_l_pressed }]
        skip_key_event: true

  - mode: w_l_pressed
    remap:
      btn_left:
        release: [{ set_mode: both_mouse_buttons_unpressed }, { release: w_l }]
      btn_right:
        release: [{ set_mode: both_mouse_buttons_unpressed }, { release: w_l }]
```
