### ISSUE TITLE
Map key combination to symbol

### ISSUE THREAD

**Issue by thetwom** [xremap/xremap#461]
My keyboard is messing the keys for "<" and ">" and "|".   Is it possible to remap a key combination (e.g. Alt-z, Alt-x, Alt-c) to these symbols. I tried unicode strings like that:
```
keymap:
  - name: Name
    remap:
       Alt-c: U203A
```
or directly ">", but all this seems not to be accepted (`keymap[0].remap: data did not match any variant of untagged enum Actions at line 4 column 8`)

I quickly scanned through all issues, but I didn't find any with similar problems.

**Comment by thetwom** [comment]
Ok, I finally succeeded, by using the corresponding key name. Seems not to be necessary that the key physically exists. For completeness, here my config (where KEY_102ND is the corresponding key in German keyboards):
```
keymap:
  - name: Name
    remap:
       Alt-z: KEY_102ND
       Alt-x: SHIFT-KEY_102ND
       Alt-c: ALT-KEY_102ND
```

In the end this does not really answer the question if one could directly map a symbol, but it works fine for me.

Thanks for all the work!
