### ISSUE TITLE
Filtering devices in configuration ignored

### ISSUE THREAD

**Issue by v-p-b** [xremap/xremap#463]
I have the following configuration:

```yaml
keymap:
  - name: debugpedal
    remap:
      KEY_A: KEY_F9
      KEY_B: KEY_F7
      KEY_C: KEY_F8
    device:
      only: ["PCsensor FootSwitch Keyboard"]
```

When I run this config xremap prints the following message:

```
Selected keyboards automatically since --device options weren't specified:
...
```

When I provide `--device "PCsensor FootSwitch Keyboard"` as a command line parameter the events are filtered as expected. I tried the same thing with device paths with the same result.

I expect the tool to obey configuration just as it obeys command line arguments. as it is documented:

https://github.com/xremap/xremap/blob/f39afb076bd5b4e087464fc5327b4fdb09826c25/README.md?plain=1#L381

May be related to #388
