### ISSUE TITLE
[ FEATURE REQUEST ] : Give "modmap" modes

### ISSUE THREAD

**Issue by Tygo-van-den-Hurk** [xremap/xremap#474]
Let's say I use the following config:
```YML

modmap:

  - name: remap
    remap:
      # none

  - name: remap
    remap: 
      KEY_XXX: KEY_YYY

keymap:
  - name: default
    mode: default
    remap:
      KEY_XXX-KEY_ZZZ: { set_mode: other }
      # other remaps...

  - name: other
    mode: other
    remap:
      KEY_XXX-KEY_ZZZ: { set_mode: default }

default_mode: default
```

Then by pressing `KEY_XXX + KEY_ZZZ` I'll be able to turn my keybindings on or off. However, I won't be able to turn the mod map on or off as it does not support modes.

I was wondering if you could add this feature.
