### ISSUE TITLE
Is it possible to use multiple keys as a modifier?

### ISSUE THREAD

**Issue by JaimeKurz** [xremap/xremap#480]
right now I have
```
keymap:
#...
    remap:
      Super-a:
        remap:
          j: [KEY_5, KEY_J]
          k: [KEY_5, KEY_k]
```
But I have to release super-a before pressing j or k for it to register.
Is there a way to treat super-a as a modifier, so super-a-j and super-a-k can be done in one motion?

**Comment by k0kubun** [comment]
Doesn't the following config work for you?

```
keymap:
#...
    remap:
      Super-a:
        remap:
          Super-j: [KEY_5, KEY_J]
          Super-k: [KEY_5, KEY_k]
```
