### ISSUE TITLE
Different command on repeated button press

### ISSUE THREAD

**Issue by toby63** [xremap/xremap#481]
Hello,

I use the following config now, for enabling push-to-talk in Mumble:

``` modmap:
    - name: Mumble1
      remap:
        PAGEDOWN:
          skip_key_event: true
          press: { launch: ["mumble", "rpc", "starttalking"] } 
          release: { launch: ["mumble", "rpc", "stoptalking"] } 
```

Everything is working well, but I would also like to have a second command that would look something like this:
``` press: { launch: ["mumble", "rpc", "starttalking"] } 
     repeatedpress: { launch: ["mumble", "rpc", "stoptalking"] } 
```

The idea is:
1. press a button (PAGEDOWN in my case) to starttalking
2. press the same button again to stoptalking
3. press the same button again to starttalking again and so on

How can I do that?
And if it isn't possible yet, consider it a Feature Request.

**Comment by k0kubun** [comment]
I'm not sure if I follow. With:

```yml
    press: { launch: ["mumble", "rpc", "starttalking"] } 
    repeatedpress: { launch: ["mumble", "rpc", "stoptalking"] } 
```

what happens when you `release` without `repeatedpress`? Do you want to make `release` an optional config and emit no event on it?

**Comment by toby63** [comment]
@k0kubun Sry for the confusion, ignore the "press" stuff, I did not think correctly about it (that press means "keep pressing").

What I want to achieve is what I have written below that:
1. press a button (PAGEDOWN in my case) to starttalking
2. press the same button again to stoptalking
3. press the same button again to starttalking again and so on

**Comment by k0kubun** [comment]
and what's an example YAML file you want to use for it?

**Comment by toby63** [comment]
@k0kubun 

I think it could be something like this:
``` 
modmap:
    - name: Mumble1
      remap:
        PAGEDOWN:
          skip_key_event: true
          click: { launch: ["mumble", "rpc", "starttalking"] } 
          repeat: { launch: ["mumble", "rpc", "stoptalking"] } 
``` 

Or this:

``` 
modmap:
    - name: Mumble1
      remap:
        PAGEDOWN:
          skip_key_event: true
          launch: ["mumble", "rpc", "starttalking"] } 
          repeat: { launch: ["mumble", "rpc", "stoptalking"] } 
```

**Comment by k0kubun** [comment]
I still don't follow how your YAML achieves what you described. (1) is fine, yes. (2) doesn't make sense because `stoptalking` is implemented under `repeat`, which is not a "click". Then you proceed to do the same thing as (2) to trigger the other command, `starttalking`, so I'm not sure which action you meant by "click the same button", `click` or `repeat`.

Based on what you described, isn't this what you need? It doesn't seem like a new feature to me.

```yml
keymap:
  - remap:
      PageDown:
        - { launch: ["mumble", "rpc", "starttalking"] }
        - { set_mode: started }
    mode: stopped
  - remap:
      PageDown:
        - { launch: ["mumble", "rpc", "stoptalking"] }
        - { set_mode: stopped }
    mode: started
default_mode: stopped
```
