### ISSUE TITLE
Scrollwheel events go through even though mapped

### ISSUE THREAD

**Issue by ModProg** [xremap/xremap#506]
I mapped
```yml
modmap:
  - remap:
      XHIRES_UPSCROLL: A
      XHIRES_DOWNSCROLL: A
      SCROLLUP: B
      SCROLLDOWN: B
      BTN_SIDE: A
```

The result is, that scrolling up or down prints `A` as expected, but additionally still scrolls. This is not the case for `BTN_SIDE` which is correctly mapped and doesn't fire "twice".

**Comment by wistoft** [comment]
Your configuration has the same effect for me (debian-kde). There are three things to say about the configuration:

1. The keys scrollup/scrolldown shouldn't be used. There's an alternative which are: xupscroll, xdownscroll.
2. The keys xupscroll and xhires_upscroll are emitted together. So mapping both would duplicate the scroll event.
3. xupscroll makes kde scrollup, while xhires_upscroll is just ignored by kde.

Putting it all together, you can use this configuration instead:

```yml
keymap:
  - remap:
      xupscroll: a
      xdownscroll: b
```

If have changed it to keymap instead, because output from modmap will be used for matching in keymap, which is probably unexpected.
