### ISSUE TITLE
How do I map a key sequence to a character?

### ISSUE THREAD

**Issue by helioloureiro** [xremap/xremap#508]
Hi,

I'm trying to make it work as before on xmodmap with the following code:

```
keycode 38 = a A a A aring Aring
```

this code snipet was mapping the KEY_A to send "a" and "A" when shift was pressed.  And "å" and "Å" when ALT was pressed as ALT+Shift.

I'm trying to make the same here.  I followed a previous discussion in thread https://github.com/xremap/xremap/issues/120 but since I don't have Ctrl_R mapped to compose, it doesn´t  work and I actually have Altr_R for it.

I tried the following:

```yaml
keymap:
  - name: Swedish 
    remap:
      Alt-a: [ "å"]
      Alt-Shift-a: [Ctrl_R, o, A] # Å
```

which doesn't work.

So how do I map a simple Alt-a to do the "aring" as before on the Xmodmap?
