### ISSUE TITLE
Remapped arrow keys behave diffferently than real arrow keys

### ISSUE THREAD

**Issue by mateosss** [xremap/xremap#586]
Hello, I am moving from using .Xmodmap in X11 to xremap in Wayland and I am having some problems. This is under Ubuntu 24.10, on a gnome wayland session.

I've remapped CapsLock+hjlk as arrows.

```yaml
keypress_delay_ms: 10
virtual_modifiers:
  - CapsLock
keymap:
  - remap:
      KEY_CAPSLOCK-KEY_J: KEY_DOWN
      KEY_CAPSLOCK-KEY_K: KEY_UP
      KEY_CAPSLOCK-KEY_H: KEY_LEFT
      KEY_CAPSLOCK-KEY_L: KEY_RIGHT
```

I have two problems:

1. When I set my key repetition times with `xset r rate 150 30` or with gsettings:
    ```bash
    gsettings set org.gnome.desktop.peripherals.keyboard delay 150
    gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
    ```
    The real arrow keys respect this but the capslock+hjkl mappings have much longer times (I would assume these are some default times).
    Playing around with `keypress_delay_ms` doesn't seem to do much with small numbers, although when I increase it to 100ms or more I can see some difference in behavior.

2. When I long-press a real arrow key like `KEY_UP`, and I then long-press `KEY_DOWN` and release `KEY_UP` I immediately start going down with repeated presses. When I repeat this with the remaps `KEY_CAPSLOCK-KEY_K` and then `KEY_CAPSLOCK-KEY_J`, just a single down press is recognized and the repetition of the down key never starts.

I have seen #189 and #491 but they didn't provide much help.

Thanks in advance for any help.
